project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!exercises/exercises.Rmd"
    - "!slides/*.qmd"

website:
  page-navigation: true
  title: "Multi-Omics BootCamp"
  description: "Homepage for Bioinformatics with R"
  site-url: "https://omicscenter.github.io/RforBioinformatics/"
  favicon: "images/hex-logo.png"

  repo-url: https://github.com/omicscenter/RforBioinformatics
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@hossainlab"
    image: "/images/bioconductor_banner.jpg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2023, Md. Jubayer Hossain"
    background: "#242B2E"
  sidebar:
    background: "#242B2E"
    logo: "images/hex-logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/chiraltraining/
        text: GitHub
      - icon: facebook
        href: https://www.facebook.com/chiralbd.org
        text: Facebook
      - icon: twitter
        href: https://twitter.com/chiralbd
        text: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/company/chiral-bangladesh/mycompany/?viewAsMember=true
        text: LinkedIn
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: about.qmd
       text: About
     - href: schedule.qmd
       text: Schedule
     - href: prework.qmd
       text: Prework
     - href: setup-guide.qmd
       text: Setup
     - href: q-and-a.qmd
       text: FAQs
     - href: license.qmd


format:
  html:
    theme: [yeti, theme.scss]
    toc: true
    code-line-numbers: true
    code-link: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: source

